FROM python:3.11-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY pyproject.toml /app/
COPY app_streamlit /app/app_streamlit

RUN adduser --disabled-password --gecos "" appuser
RUN pip install --no-cache-dir .
USER appuser

EXPOSE 8501
CMD ["streamlit", "run", "app_streamlit/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
